### ISSUE TITLE
Why Neo4J is not in the list somewhere?

### ISSUE THREAD

**Issue by geomartino** [semantalytics/awesome-semantic-web#147]
I'am new with web semantic concept and in my research, Neo4J come up pretty often.  This repo seem to be THE most complete out there so I was curious....

Good work!

**Comment by zacharywhitley** [comment]
Because Neo4J doesn't support semantic web standards with the exception of the use of the neosemantics plugin which isn't on there but I have added an issue to add it so thank you. 

I can see why you might want it there but the list is already a bit sprawling and there should be plenty of awesome-neo4j lists out there already. I've tried to avoid the more general subject of knowledge graphs, property graphs, etc.
