### ISSUE TITLE
Add  database rdfhdt to the databases

### ISSUE THREAD

**Issue by copycatK** [semantalytics/awesome-semantic-web#155]
This open source implementation of a read-only datastore for the binary HDT format promises to be very fast and through compression requiring a very small size.

**Comment by zacharywhitley** [comment]
I can see how you'd consider it a database and I would too. It's a bit like SQLite. The reason I don't list it there is because the project describes itself as a compact binary file format and not a database.  Considered as a database it's a rather poor one so rather than list it there and have people either disappointed in it as a database or confused about the different descriptions (file format vs database) I've chosen not to list it there. I'm happy to have you change my mind though.

**Comment by copycatK** [comment]
I agree so a certain extend with your analysis, but the trouble with it is that now RDF HDT is no longer present at the page at all. I can see some use cases for this solution. I would have liked to be able to find info on this product on your page, even more so because the product seems to be maintained. Maybe add it to the "Misc" category with a small description? Like:
"RDF HDT provides open-source libraries in Java and C++ to build a fast and small read-only HDT datastore solution. Accompanying analysis tools are provided"

**Comment by zacharywhitley** [comment]
I see. Looking at it how I included a link to the w3c submitted standard but not to the project page. We can take care of that. Thanks.
