### ISSUE TITLE
Reach 1000 stars

### ISSUE THREAD

**Issue by maximveksler** [semantalytics/awesome-semantic-web#68]
How can we collect 1000 starts to publish semantic web technology to more people throughout the industry ?

**Comment by zacharywhitley** [comment]
Here's a win-win. We should compile a list of places that we should promote the list, forums, users groups, etc. If it's a good place to promote the list it probably belongs on the list so win-win. We just need to start reaching out to those groups. I'm a little hesitant because barging into a forum to announce "hey check out my new shiny thing!" can bit a bit tricky.

**Comment by zacharywhitley** [comment]
How about a "not-so-awesome-semantic-web" page? We should be self critical and there is an awareness that there are still some things that need to be done as demonstrated by the recent discussion around EasierRDF. We could triage the discussion and categorize it around clarifying misunderstandings, outreach, education, technical improvement, etc.". I've always wanted to get a good list of the actual problems people were experiencing using the technology. I'm talking about the stupid stuff like "I can't find an ontology", "how do I structure my uri's", and "how do I balance mapped data stores with native data stores, Do I import, federate? What?"

**Comment by zacharywhitley** [comment]
I’m going to go and close this because the closing criteria would simply be reaching 1000 stars. I would suggest we open individual specific tickets for items that will work toward this goal.
